"""
ONNX External Weights probe model package.

The model files (model.onnx, model.data) are generated by running:
    python -m edgegate.probe_models.onnx_external.generate_onnx_external

Or during setup:
    pip install -e . && python -m edgegate.probe_models.generate_all
"""
