"""
AIMET Quantized probe model package.

BLOCKING ISSUE: This package requires real AIMET-generated fixtures.

The following files are required:
- model.onnx: Quantized ONNX model from AIMET
- model.encodings: AIMET encodings file (JSON)
- model.data: Optional external weights

These files must be generated by the actual AIMET toolkit.
Do NOT create fake/synthetic encodings files.

See: edgegate/validators/aimet.py for the blocking issue documentation.
"""

# Status: BLOCKED - No valid AIMET fixture available
AIMET_FIXTURE_AVAILABLE = False
